title: "AI Guide"
subtitle: "America–India Living, Made Easy"
name: "AI Guide"
description: "Step-by-step guides for Indians moving to the USA — paperwork, housing, transport, insurance, daily life."
url: ""  # set your custom domain if you add one later (e.g., https://aiguide.com)
baseurl: ""  # set to /<repo-name> if your repo is not username.github.io
repository: ""

theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
locale: "en-US"
logo: ""
breadcrumbs: true
search: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

author:
  name: "AI Guide"
  avatar: ""
  bio: "America–India Living, Made Easy — practical how-tos for Indians settling in the USA."
  location: "USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      comments: true
      share: true
      toc: true
      toc_sticky: true
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true

include:
  - _pages

# Analytics (optional)
# google_analytics: ""

# Social (optional)
# twitter:
#   username: ""
